repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: format
        name: Format code
        entry: make fmt
        language: system
        types: [go]
      - id: unitTest
        name: Unit tests
        entry: make unit
        language: system
        types: [ go ]
      - id: linter
        name: Linter
        entry: make lint
        language: system
        types: [ go ]