version: '3'
services:
  db:
    image: postgres:14.0-alpine
    container_name: book_store_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: book_store_user
      POSTGRES_PASSWORD: book_store_pass
      POSTGRES_DB: book_store
    restart: always
